INSERT INTO utpolis.pelicula (nombre, sinopsis, clasificacion, categoria, duracion, imagen, idioma)
VALUES ('El Origen', 'Un ladrón que roba secretos corporativos mediante el uso de tecnología para compartir sueños.',
        'PG-13', 'Ciencia Ficción', '148 min', 'el_origen.jpg', 'Inglés'),
       ('Matrix', 'Un hacker informático aprende de misteriosos rebeldes sobre la verdadera naturaleza de su realidad.',
        'R', 'Acción', '136 min', 'matrix.jpg', 'Inglés'),
       ('Interestelar',
        'Un equipo de exploradores viaja a través de un agujero de gusano en el espacio en un intento de asegurar la supervivencia de la humanidad.',
        'PG-13', 'Aventura', '169 min', 'interestelar.jpg', 'Inglés'),
       ('Avatar', 'Un marine parapléjico es enviado a la luna Pandora en una misión única.', 'PG-13', 'Ciencia Ficción',
        '162 min', 'avatar.jpg', 'Inglés'),
       ('Titanic', 'Una historia de amor trágica a bordo del infame barco Titanic.', 'PG-13', 'Drama', '195 min',
        'titanic.jpg', 'Inglés'),
       ('El Señor de los Anillos: La Comunidad del Anillo',
        'Un hobbit emprende un viaje para destruir un anillo poderoso.', 'PG-13', 'Fantasía', '178 min',
        'lotr_fellowship.jpg', 'Inglés'),
       ('Harry Potter y la Piedra Filosofal', 'Un niño descubre que es un mago y asiste a una escuela de magia.', 'PG',
        'Fantasía', '152 min', 'harry_potter.jpg', 'Inglés'),
       ('Jurassic Park', 'Un parque temático con dinosaurios clonados se convierte en un caos.', 'PG-13', 'Aventura',
        '127 min', 'jurassic_park.jpg', 'Inglés'),
       ('Star Wars: Episodio IV - Una Nueva Esperanza',
        'Un joven granjero se une a una rebelión contra un imperio galáctico.', 'PG', 'Ciencia Ficción', '121 min',
        'star_wars.jpg', 'Inglés'),
       ('El Padrino', 'La historia de una familia de la mafia italiana en Nueva York.', 'R', 'Crimen', '175 min',
        'el_padrino.jpg', 'Inglés');

INSERT INTO utpolis.sala (capacidad, numero, tipo, estatus)
VALUES (100, 1, 'Estándar', true);

INSERT INTO utpolis.asiento (numero, ocupado, sala_id)
VALUES ('A1', false, 1),
       ('A2', false, 1),
       ('A3', false, 1),
       ('A4', false, 1),
       ('A5', false, 1),
       ('A6', false, 1),
       ('A7', false, 1),
       ('A8', false, 1),
       ('A9', false, 1),
       ('A10', false, 1),
       ('B1', false, 1),
       ('B2', false, 1),
       ('B3', false, 1),
       ('B4', false, 1),
       ('B5', false, 1),
       ('B6', false, 1),
       ('B7', false, 1),
       ('B8', false, 1),
       ('B9', false, 1),
       ('B10', false, 1),
       ('C1', false, 1),
       ('C2', false, 1),
       ('C3', false, 1),
       ('C4', false, 1),
       ('C5', false, 1),
       ('C6', false, 1),
       ('C7', false, 1),
       ('C8', false, 1),
       ('C9', false, 1),
       ('C10', false, 1),
       ('D1', false, 1),
       ('D2', false, 1),
       ('D3', false, 1),
       ('D4', false, 1),
       ('D5', false, 1),
       ('D6', false, 1),
       ('D7', false, 1),
       ('D8', false, 1),
       ('D9', false, 1),
       ('D10', false, 1),
       ('E1', false, 1),
       ('E2', false, 1),
       ('E3', false, 1),
       ('E4', false, 1),
       ('E5', false, 1),
       ('E6', false, 1),
       ('E7', false, 1),
       ('E8', false, 1),
       ('E9', false, 1),
       ('E10', false, 1);

INSERT INTO utpolis.horario (hora)
VALUES ('10:00:00'),
       ('13:00:00'),
       ('16:00:00'),
       ('19:00:00'),
       ('22:00:00'),
       ('10:00:00'),
       ('13:00:00'),
       ('16:00:00'),
       ('19:00:00'),
       ('22:00:00');

INSERT INTO utpolis.funcion (fecha, horario_id, sala_id, pelicula_id, precio)
VALUES ('2024-11-14', 1, 1, 1, 80),
       ('2024-11-14', 2, 1, 2, 80),
       ('2024-11-14', 3, 1, 3, 80),
       ('2024-11-14', 4, 1, 4, 80),
       ('2024-11-14', 5, 1, 5, 80),
       ('2024-11-15', 1, 1, 6, 80),
       ('2024-11-15', 2, 1, 7, 80),
       ('2024-11-15', 3, 1, 8, 80),
       ('2024-11-15', 4, 1, 9, 80),
       ('2024-11-15', 5, 1, 10, 80);

INSERT INTO utpolis.categoria (nombre)
VALUES ('Alimentos'),
       ('Bebidas');

INSERT INTO utpolis.producto (estatus, existencia, nombre_producto, precio, tamanio, unidad, categoria_id)
VALUES (true, 50, 'Palomitas Grandes', 130, 'Grande', 'gr', 1);

